name: 'jfr-action'
description: 'JFR-action JCasC style'
inputs:
  command:
    description: Jenkinsfile-runner command, i.e; run or lint
    default: run
    required: false
  pluginstxt:
    description: plugins.txt location
    default: /plugins.txt
    required: false
  jenkinsfile:
    description: Jenkinsfile location to test
    default: /Jenkinsfile
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.command}}
    - ${{inputs.pluginstxt}}
    - ${{inputs.jenkinsfile}}