name: Java CI
on: [push]
jobs:
  jenkins-static-image-pipeline:
    runs-on: ubuntu-latest
    name: jenkins-static-image-pipeline-test
    steps:
      - uses: actions/checkout@v2
      - name: Jenkins pipeline with the static image
        id: jenkins_pipeline_image
        uses:
          Cr1t-GYM/jenkins-action-poc/jfr-static-image-action@master
        with:
          command: run
          jenkinsfile: Jenkinsfile
          pluginstxt: plugins.txt
          jcasc: jcasc.yml
  jenkins-container-pipeline:
    runs-on: windows-latest
    name: jenkins-prebuilt-container-test
    container:
      image: ubuntu
    steps:
      - run: echo "hello"
        shell: bash
#    steps:
#      - uses: actions/checkout@v2
#      - name: Jenkins pipeline in the container
#        id: jenkins_pipeline_container
#        uses:
#          Cr1t-GYM/jenkins-action-poc/jfr-container-action@master
#        with:
#          command: run
#          jenkinsfile: Jenkinsfile
#          pluginstxt: plugins.txt
#          jcasc: jcasc.yml
