name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: jfr-action JCasC test
    steps:
      - name: Jenkins pipeline
        id: jenkins_pipeline
        uses: ./jfr-action
        with:
          command: "run"
          pluginstxt: "/plugins.txt"
          jenkinsfile: "/Jenkinsfile"