name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: jfr-action JCasC test
    steps:
      - uses: actions/checkout@v2
      - name: Jenkins pipeline
        id: jenkins_pipeline
        uses: ./jfr-action
        with:
          command: "run"
          pluginstxt: "/github/workspace/plugins.txt"
          jenkinsfile: "/github/workspace/Jenkinsfile"