name: Java CI
on: [push]
jobs:
  java-jenkins-runtime-pipeline:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ] # running in different os runners
    runs-on: ${{matrix.os}}
    name: java:jenkins-runtime-pipeline
    steps:
      - uses: actions/checkout@v2
      - name: Setup Jenkins
        uses:
          jenkinsci/jenkins-setup@master # set up jenkins action environment
      - name: Jenkins plugins download
        id: jenkins_plugins_download
        uses:
          jenkinsci/jenkins-plugin-installation-action@master # download extra dependencies
        with:
          pluginstxt: plugins.txt # plugin path
      - name: Run Jenkins pipeline
        id: run_jenkins_pipeline
        uses:
          jenkinsci/jenkinsfile-runner-action@master # launch your pipeline
        with:
          command: run # jenkinsfile-runner launch option
          jenkinsfile: Jenkinsfile # Jenkinsfile path
          jcasc: jcasc.yml # jcasc path