name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    name: jfr-action JCasC test
    steps:
      # run in the on demand VM
      - uses: actions/checkout@v2
      # run in the Jenkins container which presents inside the on demand VM
      - name: Jenkins pipeline
        id: jenkins_pipeline
        uses: ./jfr-action
        with:
          command: "run"
          pluginstxt: "/github/workspace/plugins.txt"
          jenkinsfile: "/github/workspace/Jenkinsfile"
      # run in the on demand VM
      - run: ls -al /
      - uses: actions/setup-node@v3
        with:
          node-version: 14